#!/usr/bin/env python3
"""Build the fighters' sprites from the design images.

    python3 tools/build_sprites.py              # every character in tools/sprites.config.js
    python3 tools/build_sprites.py alba mario   # only these

It serves the repo on a local port, runs tools/sprite-cutter.html in headless
Google Chrome for each character and writes:
    assets/fighters/<id>.png        sprite atlas
    assets/fighters/<id>_alt.png    same atlas recoloured for mirror matches
    assets/fighters/<id>.json       frame rectangles, anchors, portraits
    assets/fighters/sprites-data.js all the .json files, loaded by index.html

Needs Google Chrome; set CHROME=/path/to/chrome if it isn't found.
To see what the cutter detected: python3 serve.py, then open
http://localhost:8765/tools/sprite-cutter.html?char=alba&debug=1
"""
import base64, functools, glob, html, http.server, json, os, re, shutil, subprocess, sys, tempfile, threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'assets', 'fighters')
CHROME_PATHS = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    r'C:\Program Files\Google\Chrome\Application\chrome.exe',
    r'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe',
    'google-chrome', 'chromium', 'chromium-browser',
]


def find_chrome():
    if os.environ.get('CHROME'):
        return os.environ['CHROME']
    for p in CHROME_PATHS:
        if os.path.isfile(p) or shutil.which(p):
            return p
    sys.exit('Google Chrome not found: set CHROME=/path/to/chrome')


class QuietHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args):
        pass

    def end_headers(self):
        self.send_header('Cache-Control', 'no-store')
        super().end_headers()


def start_server():
    srv = http.server.ThreadingHTTPServer(('127.0.0.1', 0), functools.partial(QuietHandler, directory=ROOT))
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv


def config_ids():
    src = open(os.path.join(ROOT, 'tools', 'sprites.config.js'), encoding='utf-8').read()
    return re.findall(r'^  (\w+): \{', src, re.M)


def run_cutter(chrome, port, char):
    """Run the cutter page and return its JSON result (Chrome is stopped once the DOM is dumped)."""
    url = f'http://127.0.0.1:{port}/tools/sprite-cutter.html?char={char}'
    profile = tempfile.mkdtemp(prefix='sprites-chrome-')
    cmd = [chrome, '--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check',
           f'--user-data-dir={profile}', '--virtual-time-budget=60000', '--dump-dom', url]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    timer = threading.Timer(300, proc.kill)
    timer.start()
    buf = b''
    try:
        while b'</html>' not in buf:
            chunk = proc.stdout.read1(1 << 16)
            if not chunk:
                break
            buf += chunk
    finally:
        timer.cancel()
        proc.kill()
        proc.wait()
        shutil.rmtree(profile, ignore_errors=True)
    m = re.search(r'<pre id="out">(.*?)</pre>', buf.decode('utf-8', 'replace'), re.S)
    if not m:
        raise RuntimeError(f'{char}: the cutter produced no output')
    data = json.loads(html.unescape(m.group(1)))
    if 'error' in data:
        raise RuntimeError(f"{char}: {data['error']}\n" + '\n'.join(data.get('log', [])))
    return data


def write_png(path, data_url):
    with open(path, 'wb') as f:
        f.write(base64.b64decode(data_url.split(',', 1)[1]))


def write_index():
    data = {}
    for path in sorted(glob.glob(os.path.join(OUT_DIR, '*.json'))):
        data[os.path.splitext(os.path.basename(path))[0]] = json.load(open(path, encoding='utf-8'))
    with open(os.path.join(OUT_DIR, 'sprites-data.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/build_sprites.py from the design images. Do not edit by hand.\n')
        f.write('const SPRITE_DATA = ' + json.dumps(data, separators=(',', ':')) + ';\n')
    return list(data)


def main():
    chars = sys.argv[1:] or config_ids()
    os.makedirs(OUT_DIR, exist_ok=True)
    chrome, srv = find_chrome(), start_server()
    try:
        for char in chars:
            print(f'building {char} ...', flush=True)
            r = run_cutter(chrome, srv.server_address[1], char)
            write_png(os.path.join(OUT_DIR, f'{char}.png'), r['png'])
            write_png(os.path.join(OUT_DIR, f'{char}_alt.png'), r['altPng'])
            with open(os.path.join(OUT_DIR, f'{char}.json'), 'w', encoding='utf-8') as f:
                json.dump(r['meta'], f, indent=1)
            for line in r['log']:
                print('  ' + line)
    finally:
        srv.shutdown()
    print('sprites-data.js:', ', '.join(write_index()))


if __name__ == '__main__':
    main()
